youtude_rails/student/config/routes.rb
Rails.application.routes.draw do
  resources :projects
  get 'subjects/index'
  get 'subjects/new'
  get 'subjects/edit'
  devise_for :users
  
    root 'home#index'
    # get 'students/index'
    # get 'students/show'
    post 'students/create' => "students#create"
    get 'students/new'

    resources :students
    resources :teachers
    resources :courses
   resources :subjects
    #public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'activity' => 'pages#activity'
  get 'amount' => 'pages#amount'

  # get '/home' => 'home#index'
end

youtude_rails/student/app/views/shared/_contact.html.erb
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Email address</label>
  <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>

youtude_rails/student/app/views/shared/_dummy_content.html.erb
<p class="text-center"><strong>We prioritize a well-rounded approach, blending academics with activities to foster comprehensive student development.</strong></p>
	<br>
<p class="lead">our school is dedicated to providing a high-quality education by ensuring that all teachers are competent and effective. It emphasizes a well-rounded approach to learning by giving priority to activities alongside academics, fostering holistic development among students. The school also promotes a positive and respectful environment by prioritizing good manners and behavior, creating a nurturing atmosphere for students to thrive in all aspects of their education</p>

<p class="lead2">
	School gives its students an extraordinary education, anchored in timeless values. We empower children to develop into citizens who live lives of purpose and distinction.
</p>

youtude_rails/student/app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to image_tag("logo4", alt: "logo", width:"80px" ) %>
    <%=  link_to 'Students', root_path, class: 'navbar-brand'  %>
    <%# <a class="navbar-brand" href="#"> Students</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/courses">Course</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/students">Students</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/subjects">Subject</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <%= render 'shared/links'   %>
            <li><a class="dropdown-item" href="#"></a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">something else</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-disabled="true" href="/teachers">Teachers</a>
        </li>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

youtude_rails/student/app/views/shared/_links.html.erb
<%# <h1>Students Data</h1> %>

<%= link_to 'About Us', about_path, target: '_blanck' ,style: 'color:green'  %>
<%= link_to 'Activity', activity_path, target: '_blanck' ,style: 'color:green'  %>
<%= link_to 'Amount', amount_path, target: '_blanck' ,style: 'color:green'  %>
<%= link_to 'Contact Us', contact_path, target: '_blanck' ,style: 'color:green'  %>
