page_rails/page_rails/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  #public pages routs
  get 'about_us' => 'page#about_us'
  get 'contact-us' => 'page#contact_us'
  get 'privacy-policy' => 'page#privacy_policy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

page_rails/page_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def about_us 
	end
	
	def contact_us 
	end

	def privacy_policy 
	end
	
end

page_rails/page_rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title_text = "hello world"
    @subtitle_text = "i'm lernning rails"
  end
end

page_rails/page_rails/app/controllers/page_controller.rb
class PageController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end
end

page_rails/page_rails/app/helpers/home_helper.rb
module HomeHelper
end

page_rails/page_rails/app/helpers/page_helper.rb
module PageHelper
end

page_rails/page_rails/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h2>minakshi</h2>
<p>minakshi kumari tiwari minnu kumari tiwari muhcunhduccuhcdijidchn uhcdb ucui </p>

<p>my name is minakshi kumari</p>

<%= render 'shared/links'%>
<%# <%= link_to 'about us', about_us_path  %>

<!-- #ye tarika sahi hai -->


<%#= link_to 'about us', '/about_us' %>

<%# <%= link_to nil, about_us_path %> 

page_rails/page_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PageRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <div class="container">
      <div class="row">
            <%= yield %>

      </div>
    </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

page_rails/page_rails/app/views/page/about_us.html.erb
<div class="col-lg-10 mx-auto">
	<h1 class="text-center">about page-rails</h1>

<%= render 'shared/dummy_content' %>
</div>
<%= render 'shared/links'%>

page_rails/page_rails/app/views/page/contact_us.html.erb
<div class="col-lg-10 mx-auto">
	<h1 class="text-center">about page-rails</h1>

<%= render 'shared/dummy_content' %>
</div>
<%= render 'shared/links'%>

page_rails/page_rails/app/views/page/privacy_policy.html.erb
<div class="col-lg-10 mx-auto">
	<h1 class="text-center">about page-rails</h1>

<%= render 'shared/dummy_content' %>
</div>
<%= render 'shared/links'%>

page_rails/page_rails/app/views/shared/_dummy_content.html.erb
<P class="lead">Why do we use it?
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</P>

<p class="lead">Why do we use it?
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

<p class="lead">Why do we use it?
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

page_rails/page_rails/app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'page-rails', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

page_rails/page_rails/app/views/shared/_links.html.erb
 <h1>Page</h1>

<%= link_to 'about us', about_us_path, target: 'blank', style: 'color:green;' %>
<%= link_to 'privacy policy', privacy_policy_path, target: 'blank', style: 'color:green;' %>
<%= link_to 'contact us', contact_us_path, target: 'blank', style: 'color:green;' %>