youtude_rails/student/config/routes.rb
Rails.application.routes.draw do
  resources :projects
  get 'subjects/index'
  get 'subjects/new'
  get 'subjects/edit'
  devise_for :users
  
    root 'home#index'
    # get 'students/index'
    # get 'students/show'
    post 'students/create' => "students#create"
    get 'students/new'

    resources :students
    resources :teachers
    resources :courses
   resources :subjects
    #public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'activity' => 'pages#activity'
  get 'amount' => 'pages#amount'

  # get '/home' => 'home#index'
end

youtude_rails/student/app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable,  and :omniauthable
  has_many :student_projects
  has_many :projects, through: :student_projects
  
  has_and_belongs_to_many :subjects
  # has_many :enrollments
    # has_many :subjects
  has_many :courses, through: :enrollments
    # has_many :courses
validates :name , :title , presence: true
validates :personal_email , :rool_number ,  presence: true, uniqueness: true
validates :city , :state, :country , :pincode, :address ,presence: true
end
 

youtude_rails/student/app/controllers/student_controller.rb
class StudentsController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def activity
  end

  def amount
  end
end

youtude_rails/student/app/controllers/students_controller.rb
class StudentsController < ApplicationController
before_action :set_student, only: [:edit , :update, :show , :destroy]
	def index
		@students = Student.all
	end

	def new
     @student = Student.new
	end
   
  def create
   	@student = Student.new(student_params)
       # Student.new(student_params)
   	if @student.save
   		redirect_to students_path , notice: 'Student has been created successfully'
   	else
   		render 'new'
   	end
  end

   def edit
   end

   def update
    if @student.update(student_params)
    	redirect_to students_path, notice: 'Student has been updated successfully'
    else
    	render :edit
    end
   end

   def show
   	# debugger
   end

   def destroy
      if @student.destroy
       redirect_to students_path, notice: 'Student has been deleted successfully' 
      end
   end
 
  private
   def student_params

    	params.require(:student).permit(:name, :title, :personal_email, :rool_number,:subject_id ,:city, :state, :country, :pincode, :address)
   end
  
  def set_student
       @student = Student.find(params[:id])
    rescue ActiveRecord::RecordNotFound => error
                     redirect_to students_path, notice: error
  end
   # private
   # def student_params
   # 	params.require(:student).permit(:name, :title,
   # 	 :personal_email, :rool_number, :city, :state, :country,
   # 	 :pincode, :address)
   # end  
end

youtude_rails/student/app/helpers/students_helper.rb
module StudentsHelper
end

youtude_rails/student/app/views/students/_form.html.erb
<%= form_with model: @student do |form|  %>
<div class="row">

<!--  <%# if @student.errors.any? %>
  <div class="col-lg-12">
  	<p class="lead">please fix errors below</p>
  	<%#  @student.errors.full_messages.each do |message| %>
      <p class="text-danger"><%#= message%></p>
  	<%# end %>
     
  </div>
  <%# end %> -->
     
     


	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :name, class: 'mb-2' %>
			<%= form.text_field  :name, class: 'form-control form-control-lg'%>
			  	<%  @student.errors.full_messages_for(:name).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Title, class: 'mb-2' %>
			<%= form.text_field  :title, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:title).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Personal_Email, class: 'mb-2' %>
			<%= form.email_field :personal_email, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:personal_email).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>

                 
		</div>
	</div>
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Roll_Number, class: 'mb-2' %>
			<%= form.text_field :rool_number, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:rool_number).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	 <div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Subject, class: 'mb-2' %>
	 <%= form.select :subject_id, options_from_collection_for_select(Subject.all, :id, :sub_name), {}, class: 'form-control form-control-lg' %>
   </div>
	</div>
    
</div>


<div class="row">
	<div class="col-lg-3">
		<div class="from-group">
			<%= form.label :City, class: 'mb-2' %>
			<%= form.text_field :city, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:city).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-3">
		<div class="from-group">
			<%= form.label :State, class: 'mb-2' %>
			<%= form.text_field :state, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:state).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-3">
		<div class="from-group">
			<%= form.label :Country, class: 'mb-2' %>
			<%= form.text_field :country, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:country).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-3">
		<div class="from-group">
			<%= form.label :Pincode, class: 'mb-2' %>
			<%= form.text_field :pincode, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:pincode).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Address, class: 'mb-2' %>
			<%= form.text_field  :address, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:address).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12 mt-4">
		<%= form.submit class: 'btn btn-primary btn-lg' %>

        <%= link_to "Back to Student" , students_path, class: "btn btn-outline-primary btn-lg " %>
		</div>
	</div>

<% end %>

youtude_rails/student/app/views/students/edit.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
  <h1 class="text-center">Edit Student Info</h1>
	</div>
</div>
<%= render 'form', student: @student%>

</div>

youtude_rails/student/app/views/students/index.html.erb
 <div class="col-lg-12">
 	<%= flash[:notice] %>
  <div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
  <h1 class="text-center">Listing Students</h1>
	</div>
	
  </div>

  <%= link_to "Create New student",new_student_path ,class: "btn btn-primary btn-lg mb-4 rounded-0"  %>

 <table class="table table-bordered">
	<thead>
		<tr>
		<th>Name</th>
		<th>Title</th>
        <th>Email</th>
        <th>Roll Number</th>
        <th>subject</th>
        <th>City</th>
        <th>State</th>
        <th>Country</th>
        <th>Pincode</th>
         <th>Address</th>
         <th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @students.each do |student|   %>
		<tr>
			<td><%=  student.name %></td>
			<td><%=  student.title %></td>
			<td><%= student.personal_email %></td>
			<td><%= student.rool_number %></td>
		    <td><%= student.subjects  %></td>
			<td><%= student.city %></td>
			<td><%= student.state %></td>
			<td><%= student.country %></td>
			<td><%= student.pincode %></td>
			<td><%= student.address %></td>
			<td> <%= link_to "Edit" , edit_student_path(student), class: "btn btn-primary"   %></td>

			<td> <%= link_to "View" , student_path(student), class: "btn btn-info"   %></td>

			<td> <%= link_to "Delete" , student_path(student), class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure to delete this student'}   %></td>
			<%# <td><%=student.full_address%>
		</tr>
		<% end %>

	</tbody>
 </table>
</div>

youtude_rails/student/app/views/students/new.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
  <h1 class="text-center">New Student</h1>
	</div>
</div>

<%= form_with model: @student do |form|  %>
<div class="row">

<!--  <%# if @student.errors.any? %>
  <div class="col-lg-12">
  	<p class="lead">please fix errors below</p>
  	<%#  @student.errors.full_messages.each do |message| %>
      <p class="text-danger"><%#= message%></p>
  	<%# end %>
     
  </div>
  <%# end %> -->
     
     


	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :name, class: 'mb-2' %>
			<%= form.text_field  :name, class: 'form-control form-control-lg'%>
			  	<%  @student.errors.full_messages_for(:name).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Title, class: 'mb-2' %>
			<%= form.text_field  :title, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:title).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Personal_Email, class: 'mb-2' %>
			<%= form.email_field :personal_email, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:personal_email).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>

                 
		</div>
	</div>
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Roll_Number, class: 'mb-2' %>
			<%= form.text_field :rool_number, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:rool_number).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>
</div>


<div class="row">
	<div class="col-lg-3">
		<div class="from-group">
			<%= form.label :City, class: 'mb-2' %>
			<%= form.text_field :city, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:city).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-3">
		<div class="from-group">
			<%= form.label :State, class: 'mb-2' %>
			<%= form.text_field :state, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:state).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-3">
		<div class="from-group">
			<%= form.label :Country, class: 'mb-2' %>
			<%= form.text_field :country, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:country).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-3">
		<div class="from-group">
			<%= form.label :Pincode, class: 'mb-2' %>
			<%= form.text_field :pincode, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:pincode).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Address, class: 'mb-2' %>
			<%= form.text_field  :address, class: 'form-control form-control-lg'%>
			<%  @student.errors.full_messages_for(:address).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12 mt-4">
		<%= form.submit class: 'btn btn-primary btn-lg' %>

        <%= link_to "Back to Student" , students_path, class: "btn btn-outline-primary btn-lg " %>
		</div>
	</div>

<% end %>
</div>

youtude_rails/student/app/views/students/show.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
  <h1 class="text-center"> Student Details</h1>
  <div class="row"></div>
  <div class="col-lg-6">
  	<h3 class="text-center">Personal info</h3>
  	

<p class="lead"><strong>Name:</strong> <%= @student.name %></p>
  	<p class="lead"><strong>Title:</strong> <%= @student.title %></p>
   <p class="lead"><strong>Rool Nmuber:</strong> <%= @student.rool_number %></p>
 <p class="lead"><strong>Personal Email:</strong> <%= @student.personal_email %></p>

  </div>
  <div class="col-lg-6">
  	<h3 class="text-center">Address info</h3>
  	<p class="lead"><strong>City:</strong> <%= @student.city %></p>
  	<p class="lead"><strong>State:</strong> <%= @student.state %></p>
   <p class="lead"><strong>Country:</strong> <%= @student.country %></p>
    <p class="lead"><strong>Pincode:</strong> <%= @student.pincode %></p>
 <p class="lead"><strong>Address:</strong> <%= @student.address %></p>

  </div>
  <%=  link_to 'Back to student', students_path, class: 'btn btn-outline-primary btn-lg'   %>

   <%=  link_to 'Edit Student', edit_student_path(@student), class: 'btn btn-primary btn-lg'   %>
	</div>
</div>

</div>