youtude_rails/student/config/routes.rb
Rails.application.routes.draw do
  resources :projects
  get 'subjects/index'
  get 'subjects/new'
  get 'subjects/edit'
  devise_for :users
  
    root 'home#index'
    # get 'students/index'
    # get 'students/show'
    post 'students/create' => "students#create"
    get 'students/new'

    resources :students
    resources :teachers
    resources :courses
   resources :subjects
    #public pages routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'activity' => 'pages#activity'
  get 'amount' => 'pages#amount'

  # get '/home' => 'home#index'
end

youtude_rails/student/app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :courses
  belongs_to :subject
	# has_many :students_teachers
	validates :first_name , :last_name , presence: true
validates :email , presence: true , uniqueness: true
validates :address , presence: true

end

youtude_rails/student/app/controllers/concerns/teachers_controller.rb
class TeachersController < ApplicationController

    def index
		@teachers = Teacher.all
	end

   def new
    @teacher = Teacher.new
	end
   
  def create
   	@teacher = Teacher.new(teacher_params)
    Teacher.new(teacher_params)

   	if @teacher.save
   		redirect_to teachers_path , notice: 'teacher has been created successfully'
   	else
   		render 'new'
   	end
  end

   def edit
     @teacher = Teacher.find(params[:id])
   end

   def update
   	      @teacher = Teacher.find(params[:id])
   	      if @teacher.update(teacher_params)
   	      	redirect_to teachers_path, notice: 'teacher has been updated successfully'
   	      else
   	      	render :edit
   	      end
   end

   def show
   	# debugger
   	@teacher =Teacher.find(params[:id])
   end

 def destroy
   @teacher =Teacher.find(params[:id])
      if @teacher.destroy
               redirect_to teachers_path, notice: 'Teachers has been deleted successfully'
               
            end
   end

  private
   def teacher_params
    	params.require(:teacher).permit(:first_name, :last_name, :email, :subject, :address)
   end

end

youtude_rails/student/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

    def index
		@teachers = Teacher.all
	end

   def new
    @teacher = Teacher.new
	end
   
  def create
   	@teacher = Teacher.new(teacher_params)

   	if @teacher.save
   		redirect_to teachers_path , notice: 'teacher has been created successfully'
   	else
   		render 'new'
   	end
  end

   def edit
     @teacher = Teacher.find(params[:id])
   end

   def update
   	      @teacher = Teacher.find(params[:id])
   	      if @teacher.update(teacher_params)
   	      	redirect_to teachers_path, notice: 'teacher has been updated successfully'
   	      else
   	      	render :edit
   	      end
   end

   def show
   	# debugger
   	@teacher =Teacher.find(params[:id])
   end

 def destroy
   @teacher =Teacher.find(params[:id])
      if @teacher.destroy
               redirect_to teachers_path, notice: 'Teachers has been deleted successfully'
               
            end
   end

  private
   def teacher_params
    	params.require(:teacher).permit(:first_name, :last_name, :email, :subject_id, :address)
   end

end

youtude_rails/student/app/views/teachers/_form.html.erb
<%= form_with model: @teacher do |form|  %>
<div class="row">

<!--  <%# if @student.errors.any? %>
  <div class="col-lg-12">
  	<p class="lead">please fix errors below</p>
  	<%#  @student.errors.full_messages.each do |message| %>
      <p class="text-danger"><%#= message%></p>
  	<%# end %>
     
  </div>
  <%# end %> -->
     
     


	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :first_name, class: 'mb-2' %>
			<%= form.text_field  :first_name, class: 'form-control form-control-lg'%>
			  	<%  @teacher.errors.full_messages_for(:first_name).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>

	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :last_name, class: 'mb-2' %>
			<%= form.text_field  :last_name, class: 'form-control form-control-lg'%>
			<%  @teacher.errors.full_messages_for(:last_name).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Email, class: 'mb-2' %>
			<%= form.email_field :email, class: 'form-control form-control-lg'%>
			<%  @teacher.errors.full_messages_for(:email).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>

                 
		</div>
	</div>
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Subject, class: 'mb-2' %>
	 <%= form.select :subject_id, options_from_collection_for_select(Subject.all, :id, :sub_name), {}, class: 'form-control form-control-lg' %>
   </div>
	</div>
    
</div>



</div>

<div class="row">
	<div class="col-lg-4">
		<div class="from-group">
			<%= form.label :Address, class: 'mb-2' %>
			<%= form.text_field  :address, class: 'form-control form-control-lg'%>
			<%  @teacher.errors.full_messages_for(:address).each do |message| %>
			  	  <p class="text-danger"><%= message%></p>
                 <% end %>
		</div>
	</div>
    



    
	</div>

	<div class="row">
		<div class="col-lg-12 mt-4">
		<%= form.submit class: 'btn btn-primary btn-lg' %>

        <%= link_to "Back to Teacher" , teachers_path, class: "btn btn-outline-primary btn-lg " %>
		</div>
	</div>

<% end %>

youtude_rails/student/app/views/teachers/edit.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
  <h1 class="text-center">Edit Teacher Info</h1>
	</div>
</div>
<%= render 'form', teacher: @teacher%>

</div>

youtude_rails/student/app/views/teachers/index.html.erb
<div class="col-lg-12">
 	<%= flash[:notice] %>
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
  <h1 class="text-center">Listing Teachers</h1>
	</div>
	
 </div>

 <%= link_to "Create New Teacher",new_teacher_path ,class: "btn btn-primary btn-lg mb-4 rounded-0"  %>

  <table class="table table-bordered">
	<thead>
		<tr>
		<th>Name</th>
		<th>Title</th>
        <th>Email</th>
        <th>Subject</th>
         <th>Address</th>
         <th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @teachers.each do |teacher|   %>
		<tr>
			<td><%=  teacher.first_name %></td>
			<td><%= teacher.last_name %></td>
			<td><%= teacher.email %></td>
			<td><%= teacher.subject&.sub_name %></td>
			<td><%= teacher.address %></td>
			<td> <%= link_to "Edit" , edit_teacher_path(teacher), class: "btn btn-primary"   %></td>

			<td> <%= link_to "View" , teacher_path(teacher), class: "btn btn-info"   %></td>
             <td> <%= link_to "Delete" , teacher_path( teacher), class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure to delete this student'}   %></td>

		</tr>

		<% end %>

	</tbody>
</table>
</div>

youtude_rails/student/app/views/teachers/new.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
  <h1 class="text-center">New Teacher</h1>
	</div>
</div>

<%= render 'form', teacher: @teacher%>
</div>

youtude_rails/student/app/views/teachers/show.html.erb
<div class="col-lg-12">
	<div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
  <h1 class="text-center"> Teacher Details</h1>
  <div class="row"></div>
  <div class="col-lg-6">
  	<h3 class="text-center">Personal info</h3>
  	

<p class="lead"><strong>Name:</strong> <%= @teacher.first_name %></p>
  	<p class="lead"><strong>Title:</strong> <%= @teacher.last_name %></p>
   
 <p class="lead"><strong> Email:</strong> <%= @teacher.email %></p>
   <p class="lead"><strong>Subject:</strong> <%= @teacher.subject.sub_name %></p>

  </div>
  <div class="col-lg-6">
  	<h3 class="text-center">Address info</h3>
  	
 <p class="lead"><strong>Address:</strong> <%= @teacher.address %></p>

  </div>
  <%=  link_to 'Back to Teacher', teachers_path, class: 'btn btn-outline-primary btn-lg'   %>

   <%=  link_to 'Edit Teacher', edit_teacher_path(@teacher), class: 'btn btn-primary btn-lg'   %>
	</div>
</div>

</div>